### ISSUE TITLE
Someting odd about VRPSPD Dethloff and Rieck instances

### ISSUE THREAD

**Issue by VictorTiezzi** [c4v4/instances#1]
👋 Hello, i'm Victor (@VictorTiezzi)
i'm studying about VRPSPD and i came up here trying to found the Dethloff CON3-0 instance, but i found the same error in instance that i aredy have.

https://github.com/c4v4/instances/blob/01a70dce214e6f24de441e54aacce35b1cb8844b/VRPSPD/INSTANCES/D/CON3-0.vrpspd#L63

you have any ideia where i can find or fix this CON3-0 instance?

i've noticed that Rieck R6 (a rounded Dethloff instances) have error that:
1 - Switch the pickup and delivery colluns, and

https://github.com/c4v4/instances/blob/01a70dce214e6f24de441e54aacce35b1cb8844b/VRPSPD/INSTANCES/D/CON3-0.vrpspd#L64

https://github.com/c4v4/instances/blob/01a70dce214e6f24de441e54aacce35b1cb8844b/VRPSPD/INSTANCES/R6/CON3-0.vrpspd#L63

2 - The distance matrix have inconsistent data compared to Dethloff

https://github.com/c4v4/instances/blob/01a70dce214e6f24de441e54aacce35b1cb8844b/VRPSPD/INSTANCES/D/CON3-0.vrpspd#L10-L12

https://github.com/c4v4/instances/blob/01a70dce214e6f24de441e54aacce35b1cb8844b/VRPSPD/INSTANCES/R6/CON3-0.vrpspd#L9-L11

i can fix it for you but for the CON3-0 missing data we have only the rouded data (swaped):

https://github.com/c4v4/instances/blob/01a70dce214e6f24de441e54aacce35b1cb8844b/VRPSPD/INSTANCES/R6/CON3-0.vrpspd#L62

we can put this information, but will not be the original data

Node: 2 
Pickup: 101600
Delivery: 109400

Thanks in advance 👍

**Comment by c4v4** [comment]
Hi!

Thank you very much for letting me know!
I'm sorry you stumbled across this repository, it's not really well maintained (It's just a bucket where I collect instances that I find myself searching for ^^)

I you are interested, the original source of the these instances is Helsgaun's [LKH-3 website](http://webhotel4.ruc.dk/~keld/research/LKH-3/). I'll add a readme stating that (at the moment they have been moved under LKH-3 directory).

I also added a set of instances I have generated for a project I'm working on.
Regarding the CON3-0, I should have fixed both in "LKH-3" version and in "mine". 
Let me kown if you find any other issue.

Thanks again!
Francesco

**Comment by c4v4** [comment]
Regarding Rieck R6 CON3-0, I have not use it myself, it was included in the set of instances I got from the LKH-3 website (and I have not dig into how they have been generated yet). 

If you find any fix or improvement, feel free to make a pull request for it ^^

Francesco

**Comment by VictorTiezzi** [comment]
👋 Hi, Francesco.

I've never heard of this site, I wish I'd found it sooner 🤣, thanks for the link.

I am a Master's student in Applied Informatics at the University of Fortaleza in Brazil and my final paper are on the Vehicle Routing Problem with Simultaneous Pickup and Delivery (VRPSPD) and my Master's paper (what im workin on) is about a fuel cost on the VRPSPD or Green-VRPSPD.

Is good too know, find someone interested in this problem to help and share Knowledge 👍

First thing i want to share that i was wrong about the R6 matrix reading better the article 🤣 in Springer Link (https://link.springer.com/content/pdf/10.1007/BF03342743.pdf) 
that was discribe how the made the instances and the matrix is asymmetric (article, 5.1 Benchmark instances, page 84)
BUT the data about pickup and delivery still swaped and i didn't know if that was on purpose using this formula:
ri := min{(xi/yi), (yi/xi)}, di := ri δi, pi := δi − di
xi and yi are x- and y-coordinate values of i;
δi is the original demand of the underlying problem instance;
and ri is rounded to the second decimal place
(article, 5.1 Benchmark instances, page 85)

Anyway, thanks for correcting the CON3-0 data 👍
Victor
